server:
  port: 8081

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sjhealthy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234
  resources:
    static-locations: classpath:/static/
  servlet:
    multipart:
      enabled: true #첨부파일

  jpa:
    hibernate:
      ddl-auto: update #엔티티와 테이블이 정상 매핑되었는지만 확인, 정상매핑 시 실행 비정상 매핑 시 에러발생 validate
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 8.x용 Hibernate Dialect 설정





  logging:
    level:
      org:
        hibernate:
          type:
            descriptor:
              sql: trace
